//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~//
//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ users ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~//
###
POST http://localhost:9000/api/users HTTP/1.1
Content-Type: application/json

{
    "name": "Emerson Vera",
    "age": "24",
    "email": "emersonvera@gmail.com"
}
###
GET http://localhost:9000/api/users HTTP/1.1
###
GET http://localhost:9000/api/users/652b2568564ae20408bcc56a HTTP/1.1
###
PUT http://localhost:9000/api/users/652c729a33869b5c169f6701 HTTP/1.1
Content-Type: application/json

{
    "name": "Emerson Vera",
    "age": "24"
}
###
DELETE http://localhost:9000/api/users/652c725733869b5c169f66fc HTTP/1.1

//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~//
//~~~~~~~~~~~~~~~~~~~~~~~~~~~~ facilities ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~//
###
POST http://localhost:9000/api/facilities HTTP/1.1
Content-Type: application/json

{
    "name": "Data"
}
###
GET http://localhost:9000/api/facilities HTTP/1.1
###
GET http://localhost:9000/api/facilities/Wi-fi HTTP/1.1
###
PUT http://localhost:9000/api/facilities/Data HTTP/1.1
Content-Type: application/json

{
    "newName": "Data"
}
###
DELETE http://localhost:9000/api/facilities/Data HTTP/1.1
//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~//
//~~~~~~~~~~~~~~~~~~~~~~~~~~~~ typeEnvironments ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~//
###
POST http://localhost:9000/api/typeEnvironments HTTP/1.1
Content-Type: application/json

{
    "name": "Auditorio"
}
###
GET http://localhost:9000/api/typeEnvironments HTTP/1.1
###
GET http://localhost:9000/api/typeEnvironments/Piso HTTP/1.1
###
PUT http://localhost:9000/api/typeEnvironments/Piso HTTP/1.1
Content-Type: application/json

{
    "newName": "Laboratorio"
}
###
DELETE http://localhost:9000/api/typeEnvironments/Laboratorio HTTP/1.1
//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~//
//~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Environments ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~//
###
POST http://localhost:9000/api/Environments HTTP/1.1
Content-Type: application/json

{
    "name": "690A",
    "capacity": 50,
    "description": "Es un aula mediana con buena ventilacion",
    "active": true,
    "enabled": true,
    "typeEnvironment": "Aula",
    "facility": ["Data"]
}
###
GET http://localhost:9000/api/Environments?type=Aula&capacity=50 HTTP/1.1
###
GET http://localhost:9000/api/Environments/690A  HTTP/1.1
###
PUT http://localhost:9000/api/Environments/690A HTTP/1.1
Content-Type: application/json

{
    "newName":"690B",
    "enabled": false
}
###
DELETE http://localhost:9000/api/Environments/690A HTTP/1.1
